# Site settings
title: Mckenzie Langefeld | Percussionist
email: mckenzielangefeld@gmail.com
url: https://mckenzielangefeld.com
description: "Hi there! I'm Mckenzie, a percussionist in the bay area. (If you don't know what a percussionist is, I'd love to tell you more.) If you have any questions about gigs/performances, piano, percussion, or drum set lessons, contact me here, ​can't wait to hear from you!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000'
  primary-bright: '#fff'
  links: '#219ab3'

# Footer settings
footer: Jonny Langefeld

twitter_username: kenzielangefeld
instagram_username:  kenzielangefeld
linkedin_username: mckenzielangefeld
youtube_username: UCmZehBz7msGj8rw7iWKLirg
facebook_username: mckenziesmusicstudio

# Build settings
markdown: kramdown

collections:
  - sections

collections:
  sections:
    order:
      - bio.md
      - lessons.md
      - media.md
      - performances.md
      - contact.md

plugins:
  - jekyll-feed
  - jekyll-paginate
permalink: /blog/:title
paginate: 6
paginate_path: "/blog/page:num/"
